import { existsSync, readFileSync } from 'node:fs'

const app = readFileSync('src/App.jsx', 'utf8')
const center = readFileSync('src/components/NotificationCenter.jsx', 'utf8')
const api = readFileSync('src/api.js', 'utf8')
const css = readFileSync('src/styles.css', 'utf8')
const html = readFileSync('index.html', 'utf8')
const nginx = readFileSync('nginx.conf', 'utf8')
const sw = readFileSync('public/notification-sw.js', 'utf8')
const manifest = readFileSync('public/manifest.webmanifest', 'utf8')
const support = readFileSync('src/pages/Support.jsx', 'utf8')
const version = readFileSync('src/version.js', 'utf8')

let bad = 0
const check = (ok, label) => {
  if (!ok) bad++
  console.log(`  ${ok ? '✓' : '✗'} ${label}`)
}

console.log('\n--- центр браузерних сповіщень 1.31.5 ---')
check(app.includes("import { NotificationCenter }") && app.includes('<NotificationCenter />'), 'центр сповіщень підключений глобально в панелі')
check(api.includes("request('/notifications/poll'") && api.includes("request('/notifications/read-all'"), 'frontend має poll/read API центру')
check(center.includes("'product.created'") && center.includes("tone: 'product'"), 'новий товар має окремий тип і звук')
check(center.includes("'order.created'") && center.includes("tone: 'order'"), 'нове замовлення має окремий тип і звук')
check(center.includes("'order.message'") && center.includes("tone: 'orderMessage'"), 'повідомлення замовлення має окремий звук')
check(center.includes("'support.message'") && center.includes("tone: 'support'"), 'повідомлення підтримки має окремий звук')
check(center.includes('SOUND_MASTER_GAIN = 0.98') && center.includes('createDynamicsCompressor') && center.includes('frequency * 2'), 'звук використовує high-output master, компресію та гармоніки для високої сприйманої гучності')
check(center.includes('Notification.requestPermission()') && center.includes('permission === \'denied\''), 'дозвіл браузера запитується лише явною дією та обробляє блокування')
check(center.includes('iPhone|iPad|iPod') && center.includes("display-mode: standalone"), 'врахована PWA-вимога Safari на iPhone/iPad')
check(center.includes('Firefox:') && center.includes('Edge:') && center.includes('Chrome:') && center.includes('Safari:'), 'є підказки для основних браузерів')
check(center.includes("navigator.serviceWorker.register('/notification-sw.js'"), 'system popup використовує service worker')
check(center.includes('LEADER_KEY') && center.includes('LEADER_TTL'), 'кілька вкладок не дублюють звук і popup')
check(center.includes('document.hidden || !document.hasFocus()'), 'native popup не дублює foreground UI')
check(center.includes('initialized.current') && center.includes('fullRefresh'), 'старі події після відкриття панелі не програються як нові')
check(html.includes('manifest.webmanifest') && existsSync('public/icon-192.png') && existsSync('public/icon-512.png'), 'PWA manifest та іконки входять у збірку')
check(manifest.includes('"display": "standalone"'), 'manifest підтримує standalone режим')
check(nginx.includes('location = /notification-sw.js') && nginx.includes('no-store'), 'service worker не застрягає в кеші після deploy')
check(sw.includes("pathname.startsWith('/app')") && sw.includes('clients.openWindow'), 'клік popup не перехоплює клієнтський Mini App')
check(css.includes('.notification-popover') && css.includes('.notification-nudge') && css.includes('@media (max-width: 760px)'), 'центр і permission prompt адаптовані під ПК та телефон')
check(center.includes('TOAST_AUTO_DOCK_MS = 15000'), 'toast через 15 секунд згортається в overlay-кнопку')
check(center.includes('slice(0, 3)') && center.includes('notification-toast-overflow'), 'до трьох toast видно шарами, решта згортається в один стек')
check(center.includes('onMouseEnter={onHoverExpand}') && center.includes('notification-toast-scroll'), 'наведення розгортає прокручуваний список')
check(center.includes('notification-toast-dock') && center.includes('onClick={onPinExpand}'), 'overlay-кнопка повертає список сповіщень')
check(css.includes('.notification-toast-stage') && css.includes('.notification-toast-dock') && css.includes('notification-toast-attention'), 'toast-стек та attention-анімація оформлені в CSS')
check(css.includes('grid-template-columns: minmax(0, 1fr) 40px auto'), 'мобільна шапка має окремі колонки для бренду, дзвіночка і меню')
check(support.includes("params.get('thread')") || support.includes("get('thread')"), 'сповіщення підтримки може відкрити конкретну сесію')
check(center.includes('filter((item) => !item.read)') && center.includes('current.filter((entry) => entry.id !== item.id)'), 'прочитані події одразу зникають із робочої черги')
check(center.includes('nextUnread < unreadRef.current') && center.includes('await fullRefresh()'), 'інша вкладка та видалення джерела синхронізують список')
check(app.includes('brand-label') && css.includes('.brand-label') && css.includes('white-space: nowrap'), 'назва магазину і дзвіночок мають стабільну однорядкову розмітку')

check(css.includes('.sidebar {') && css.includes('z-index: 200') && css.includes('isolation: isolate'), 'popover сповіщень має власний верхній stacking-context і не провалюється під таблицю')
check(css.includes('padding-right: 76px') && css.includes('width: 48px') && css.includes('right: 10px'), 'згорнута кнопка живе у правому safe-rail і не перекриває дії замовлення')
check(css.includes('background: #171420') && css.includes('background: #1d192a'), 'popover та непрочитані елементи мають непрозорий фон без просвічування контенту')
check(center.includes("import { createPortal } from 'react-dom'") && center.includes('document.body'), 'нижній toast/dock винесений portal-ом із sidebar і не кліпиться')
check(center.includes('Старі непрочитані після перезавантаження') && center.includes('setToastDocked(true)'), 'непрочитані після reload відновлюють нижній dock без повторного звуку')
check(css.includes('z-index: 1200') && css.includes('background: #1d1929'), 'toast/dock гарантовано видимі поверх сторінки та мають непрозорий фон')
check(version.includes("APP_VERSION = '1.31.5'"), 'версія панелі 1.31.5')

console.log(`\nСПОВІЩЕННЯ UX: ${bad === 0 ? 'усе витримано' : `ПРОВАЛЕНО: ${bad}`}`)
process.exit(bad ? 1 : 0)
